### ISSUE TITLE
Profile Photos + Names

### ISSUE THREAD

**Issue by i1skn** [celo-org/wallet#18]
# What's important about this?
Users can see the profile photo and name of someone they are sending to

# What is "done"?
* Figma design for onboarding and settings: https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet-Refresh?node-id=2806%3A0
* Figma design for updated list items (Recipient list, transaction feed): https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet-Refresh?node-id=986%3A4151
* Requirements: https://docs.google.com/document/d/15Vyai_T7r-6zeHdMx5DewC9oZ6AbPt66cVKoh2iEtcw/edit
* Backend design: https://docs.google.com/document/d/16VBKG68oTY5hUpjLUakYO788GfPEZyqKFSM15bu7Ca0/edit

# What's involved in doing this work?
- [x] Uploading the image to the CIP0008 service from Valora celo-org/celo-monorepo#6604 
- [x] Update Contact List UI when someone is trying to send celo-org/celo-monorepo#6890
- [x] Show Contact details in transaction feed celo-org/celo-monorepo#6605 
- [ ] Cache invalidation in the app
- [x] Update Request/Send Flow to display Name and Profile Pic celo-org/celo-monorepo#6890 and celo-org/celo-monorepo#6605
- [ ] Update permissions for existing transactions sent by users so their name and profile pic start appearing in their receiver’s feeds 
- [ ] update graphQL to use account address instead of just wallet address
